Id: Bandisoft.Bandizip
Publisher: Bandisoft
Name: Bandizip
Version: 7.06
License: Bandizip License Policy
InstallerType: EXE
LicenseUrl: https://www.bandisoft.com/bandizip/help/license-policy/
AppMoniker: bandizip
Tags: bandizip, 7z, zip, rar, archiver, unachiver
Description: Yet another typical ZIP archiver
Homepage: https://www.bandisoft.com/bandizip/
Installers:
  - Arch: x64
    Url: https://ux-dl.bandisoft.com/bandizip.std/BANDIZIP-SETUP-STD-ALL.EXE
    Sha256: FAA3F8E15FEF4506D982DCE1DA37D29D9BF2FF33A31237E8D31D2ADABDD4A1FF
    Switches:
        Silent: /S
        SilentWithProgress: /S
