Id: Microsoft.WindowsTerminal
Name: Windows Terminal
AppMoniker: Terminal
Version: 1.0.1401.0
Publisher: Microsoft
Author: Microsoft
Homepage: https://github.com/microsoft/terminal
License: MIT
LicenseUrl: https://github.com/microsoft/terminal/blob/master/LICENSE
Description: Windows Terminal v1.0.1401.0
InstallerType: Msix
Installers:
  - Arch: x64
    Url: https://github.com/microsoft/terminal/releases/download/v1.0.1401.0/Microsoft.WindowsTerminal_1.0.1401.0_8wekyb3d8bbwe.msixbundle
    Sha256: 1017c8ff310e4cb4fb843de26c93baa170fe5a4764065d9faa25a45a6d724514
    SignatureSha256: 361ead03a450747e1e7db0986305a2171ad479953a89c39c3789827da28bc2fe

